#---------------------------------------------------------------------------------
# Build stage
#---------------------------------------------------------------------------------
FROM rust:latest as builder
WORKDIR /usr/src/app
COPY . .
RUN sed -i "s/name = .*/name = \"app\"/g" Cargo.toml
RUN cargo build --release --bin app
#---------------------------------------------------------------------------------

#---------------------------------------------------------------------------------
# Runtime stage
#---------------------------------------------------------------------------------
FROM debian:buster-slim as runtime

# Use this to install extra dependencies needed to run your app.
# RUN   apt-get update && \
#       apt-get install -y extra-runtime-dependencies && \
#       rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/src/app/target/release/app /usr/local/bin/app

CMD ["/usr/local/bin/app"]
#---------------------------------------------------------------------------------