#---------------------------------------------------------------------------------
# Build stage
#---------------------------------------------------------------------------------
FROM rust:latest as builder
ARG APP_NAME

WORKDIR /usr/src/${APP_NAME}

COPY . .

RUN cargo install --path .
#---------------------------------------------------------------------------------



#---------------------------------------------------------------------------------
# Runtime stage
#---------------------------------------------------------------------------------
FROM debian:buster-slim as runtime
ARG APP_NAME

# RUN   apt-get update && \
#       apt-get install -y extra-runtime-dependencies && \
#       rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/local/cargo/bin/${APP_NAME} /usr/local/bin/${APP_NAME}

ENV RUNTIME_CMD=/usr/local/bin/${APP_NAME}

CMD $RUNTIME_CMD
#---------------------------------------------------------------------------------